from time import sleep
t= ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atletico PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport', 'Vitória', 'Curitiba', 'Avaí', 'Ponte Preta', 'Atlético GO')
print('Os Cinco Primerios:')
print('=-'*30)
print(t[0:5])
sleep(2)
print('Os últimos quatro:')
print('=-'*30)
print(t[16:])
sleep(2)
print('Em ordem alfabética:')
print('=-'*30)
print(sorted(t))
sleep(2)
print('Posição do Chapecoense')
print('=-'*30)
print(f'{t.index("Chapecoense")+1}ª posição')